@baseUrl = http://localhost:3000

@urlPath = api

###
POST {{baseUrl}}/{{urlPath}}/admin/auth/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "email":"khkhd@gmail.com",
    "password":"8772123d"
}
